### ISSUE TITLE
京东版本9.2.0脚本报错

### ISSUE THREAD

**Issue by csdjl88** [roceys/JD#2]
最新版的脚本在京东APP 版本9.2.0 执行的时候报错

**Comment by roceys** [comment]
提示啥？

**Comment by csdjl88** [comment]
https://s1.ax1x.com/2020/10/31/BUYxPI.png
报错如上

**Comment by Peyet** [comment]
京东 9.0.0 报错

Wrapped java.lang.ArrayIndexOutOfBoundsException: length=3; index=3 (/storage/emulated/0/脚本/jd.js#1)
Wrapped java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
    at /storage/emulated/0/脚本/jd.js:1:0
    at /storage/emulated/0/脚本/jd.js:1:0
    at getTask (/storage/emulated/0/脚本/jd.js:1:0)
    at doTask (/storage/emulated/0/脚本/jd.js:1:0)
    at /storage/emulated/0/脚本/jd.js:1:0

**Comment by lero007** [comment]
> 京东 9.0.0 报错
> 
> Wrapped java.lang.ArrayIndexOutOfBoundsException: length=3; index=3 (/storage/emulated/0/脚本/jd.js#1)
> Wrapped java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
> at /storage/emulated/0/脚本/jd.js:1:0
> at /storage/emulated/0/脚本/jd.js:1:0
> at getTask (/storage/emulated/0/脚本/jd.js:1:0)
> at doTask (/storage/emulated/0/脚本/jd.js:1:0)
> at /storage/emulated/0/脚本/jd.js:1:0

+1
